name: JoinCommands
main: Distemi\JoinCommands\Main
description: Join commands
version: 0.2.0
api: 5.0.0
author: Distemi
commands:
 joincommands:
  description: "Reload plugin JoinCommands."
  permission: joincommands.reload
  aliases:
  - jc
  - JoinCommands
permissions:
 joincommands.reload:
  description: "Reload plugin JoinCommands."
  default: op